---
- name: Create Docker Container and Update APT packages
  hosts: localhost  # Run tasks locally
  gather_facts: false  # Skip gathering facts about the local machine

  tasks:
    - name: Create Docker Container
      docker_container:
        name: my_container
        image: my_image
        state: started
    - name: Run task inside the Docker Container
      command: "your_command_here"
      delegate_to: my_container
