---
- name: Create Docker Container and Update APT packages
  hosts: 172.27.83.5
  gather_facts: false

  tasks:
    - name: Create Docker Container
      docker_container:
        name: my_container
        image: ubuntu:20.04
        state: started
        ports: "2222:22"
        volumes:
          - /etc/ssh/sshd_config:/etc/ssh/sshd_config
        command: sleep infinity
      notify:
        - Stop and Remove Docker Container

    - name: Run a simple command (argv)
      community.docker.docker_container_exec:
        container: my_container
        argv:
          - /bin/bash
          - "-c"
          - "ls -lah > /dev/stderr"
        chdir: /root
      register: result

  handlers:
    - name: Stop and Remove Docker Container
      block:
        - name: Check if the task failed
          fail:
            msg: "Task failed, stopping and removing the container"
          when: result is failed

        - name: Stop Docker Container
          docker_container:
            name: my_container
            state: stopped

        - name: Remove Docker Container
          docker_container:
            name: my_container
            state: absent
      ignore_errors: true
