---
- name: Create Docker Container and Update APT packages
  hosts: 172.27.83.5
  gather_facts: false
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: Install requests library
      pip:
        name: "{{item}}"
        executable: pip3
      with_items:
        - docker-py
        - requests
        - docker-compose
    - name: Restart services
      community.docker.docker_compose:
        project_src: /home/sures/ansible-semaphore/ansible_semaphore/jenkins
        build: false
        state: present
      register: output