---
- name: Create Docker Container and Update APT packages
  hosts: 172.27.83.5  # Run tasks locally
  gather_facts: false  # Skip gathering facts about the local machine

  tasks:
    - name: Create Docker Container
      docker_container:
        name: my_container
        image: ubuntu:20.04
        state: started
        ports: "2222:22"
        volumes:
          - /etc/ssh/sshd_config:/etc/ssh/sshd_config
        command: sleep infinity
      ignore_errors: yes  # Ignore errors and proceed to the next task even if this one fails

    - name: Run a simple command (argv)
      community.docker.docker_container_exec:
        container: my_container
        argv:
          - /bin/bash
          - "-c"
          - "ls -lah > /dev/stderr"
        chdir: /root
      register: result

  # Block to handle cleanup if any task fails
  block:
    - name: Stop Docker Container
      docker_container:
        name: my_container
        state: stopped
      when: result is failed  # Only run this task if the previous task failed

    - name: Remove Docker Container
      docker_container:
        name: my_container
        state: absent
      when: result is failed  # Only run this task if the previous task failed

  always:
    - name: Cleanup Temporary Files or Tasks
      # Add any additional cleanup tasks that should always run
