---
- name: Create Docker Container and Update APT packages
  hosts: 172.27.83.5
  gather_facts: false
  tasks:
    - name: Remove
      shell: 
        cmd: pip3 uninstall docker docker-py docker-compose docker-compose-plugin -y
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"
          - requests
    - name: Restart services
      docker_compose:
        project_src: /home/sures/ansible-semaphore/ansible_semaphore/jenkins
        build: false
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3
      register: output