---
- name: Create Docker Container and Update APT packages
  hosts: 172.27.83.5  # Run tasks locally
  gather_facts: false  # Skip gathering facts about the local machine

  tasks:
    - name: Create Docker Container
      docker_container:
        name: my_container
        image: ubuntu:20.04
        state: started
        ports: "2222:22"
        volumes:
          - /etc/ssh/sshd_config:/etc/ssh/sshd_config
        command: sleep infinity

    - name: Run a simple command (argv)
      docker.docker_container_exec:
        container: my_container
        argv:
          - /bin/bash
          - "-c"
          - "ls -lah > /dev/stderr"
        chdir: /root
      register: result
